services:
  - type: web
    name: farmacia-backend
    env: python
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn farmacia_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: farmacia-db
          property: connectionString
  
  - type: web
    name: farmacia-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
